from enum import StrEnum

class ArmaReforgerExecutableFlag(StrEnum):
    """Arma Reforger CLI startup flags."""

    # -- General --------------------------------------------------------------

    LOG_LEVEL = "-logLevel"
    BIND_IP = "-bindIP"
    GAME_HOST = "-gproj"
    GAME_PORT = "-gamePort"
    STEAM_PORT = "-steamPort"
    A2S_ADDRESS = "-a2s"
    A2S_PORT = "-a2sPort"
    CONFIG_FILE = "-config"
    PROFILE_DIR = "-profile"
    LOGS_DIR = "-logsDir"
    LIMIT_FPS = "-maxFPS"
    RCON_HOST = "-rcon"
    RCON_PORT = "-rconPort"
    RCON_PASSWORD = "-rconPassword"
    ADDONS = "-addons"
    SCENARIO = "-scenario"
    AUTO_RELOAD = "-autoreload"
    SERVER_ID = "-serverId"
    SERVER_REGION = "-region"
    LOAD_SESSION_SAVE = "-loadSessionSave"
    FORCE_SESSION_LOAD = "-forceSessionLoad"
    ADDONS_DIR = "-addonsDir"
    ADDON_DOWNLOAD_DIR = "-addonDownloadDir"
    ADDON_TEMP_DIR = "-addonTempDir"
    BACKEND_DISABLE_STORAGE = "-backendDisableStorage"
    BACKEND_FRESH_SESSION = "-backendFreshSession"
    BACKEND_LOCAL_STORAGE = "-backendLocalStorage"
    FREEZE_CHECK = "-freezeCheck"
    FREEZE_CHECK_MODE = "-freezeCheckMode"
    CFG = "-cfg"
    LANGUAGE = "-language"
    NO_BACKEND = "-noBackend"
    NO_SOUND = "-noSound"
    NO_SPLASH = "-noSplash"
    NO_THROW = "-noThrow"
    SINGLE_THREADED_UPDATE = "-singleThreadedUpdate"
    WORLD = "-world"

    # -- Hosting --------------------------------------------------------------

    A2S_IP_ADDRESS = "-a2sIpAddress"
    AUTOSHUTDOWN = "-autoshutdown"
    ENABLE_NIGHT_GRAIN = "-enableNightGrain"
    LIST_SCENARIOS = "-listScenarios"
    KEEP_SESSION_SAVE = "-keepSessionSave"
    LOG_STATS = "-logStats"
    LOG_VOTING = "-logVoting"
    MAX_FPS = "-maxFPS"
    PLAYER_LIMITS = "-playerLimits"
    SERVER = "-server"
    ADDONS_VERIFY = "-addonsVerify"
    ADDONS_REPAIR = "-addonsRepair"

    # -- Network Tuning -------------------------------------------------------

    NDS = "-nds"
    NWK_RESOLUTION = "-nwkResolution"
    RPL_TIMEOUT_MS = "-rpl-timeout-ms"
    STAGGERING_BUDGET = "-staggeringBudget"
    STREAMING_BUDGET = "-streamingBudget"
    STREAMS_DELTA = "-streamsDelta"

    # -- Debug ----------------------------------------------------------------

    AI_LIMIT = "-AILimit"
    AI_PARTIAL_SIM = "-AIPartialSim"
    CREATE_DB = "-createDB"
    DEBUGGER = "-debugger"
    DEBUGGER_PORT = "-debuggerPort"
    DISABLE_AI = "-disableAI"
    DISABLE_CRASH_REPORTER = "-disableCrashReporter"
    DISABLE_NAVMESH_STREAMING = "-disableNavmeshStreaming"
    DISABLE_SHADERS_BUILD = "-disableShadersBuild"
    GENERATE_SHADERS = "-generateShaders"
    RPL_ENCODE_AS_LONG_JOBS = "-rplEncodeAsLongJobs"
    JOBSYS_SHORT_WORKER_COUNT = "-jobsysShortWorkerCount"
    JOBSYS_LONG_WORKER_COUNT = "-jobsysLongWorkerCount"
    KEEP_NUM_OF_LOGS = "-keepNumOfLogs"
    LOG_RDB_CHECKSUM = "-log-rdb-checksum"
    LOG_SCR_CHECKSUM = "-log-scr-checksum"
    LOG_APPEND = "-logAppend"
    LOG_FS = "-logFS"
    LOG_TIME = "-logTime"
    KEEP_CRASH_FILES = "-keepCrashFiles"
    MINIDUMP = "-minidump"
    SCRIPT_AUTHORIZE_ALL = "-scriptAuthorizeAll"
    SILENT_CRASH_REPORT = "-silentCrashReport"
    VM_ERROR_MODE = "-VMErrorMode"

    # -- Profiling ------------------------------------------------------------

    CHECK_INSTANCE = "-checkInstance"
