from typing import Protocol
from pathlib import Path

class SupervisorLike(Protocol):
    """Minimal interface for interacting with the Supervisor"""

    def queue_start(self) -> None: ...
    def queue_shutdown(self) -> None: ...
    def queue_restart(self) -> None: ...
    def queue_reload(self, config_path: str | Path) -> None: ...
