from armaden.framework.runtime.supervisor.task.enums.task_thread_policy import TaskThreadingPolicy
from armaden.framework.runtime.supervisor.task.types import TaskCallback, TaskStatusCallback
from typing import Protocol, Self


class TaskProtocol(Protocol):
    @property
    def name(self) -> str | None: ...

    @property
    def description(self) -> str | None: ...

    @property
    def initialize(self) -> TaskCallback | None: ...

    @property
    def run(self) -> TaskCallback: ...

    @property
    def shutdown(self) -> TaskCallback | None: ...

    @property
    def status(self) -> TaskStatusCallback | None: ...

    @property
    def threading_policy(self) -> TaskThreadingPolicy: ...

    @property
    def auto_restart(self) -> bool: ...


class TaskBuilderInterface(Protocol):
    def name(self, value: str | None) -> Self: ...

    def description(self, value: str | None) -> Self: ...

    def on_initialize(self, callback: TaskCallback) -> Self: ...

    def on_run(self, callback: TaskCallback) -> Self: ...

    def on_shutdown(self, callback: TaskCallback) -> Self: ...

    def on_status(self, callback: TaskStatusCallback) -> Self: ...

    def exclusive_thread(self) -> Self: ...

    def shared_thread(self) -> Self: ...

    def with_auto_restart(self) -> Self: ...

    def build(self) -> TaskProtocol: ...
