from typing import Protocol


class CacheIndexProtocol(Protocol):
    def all_keys(self) -> list[str]: ...

    def expired_keys(self) -> list[str]: ...

    def flush(self) -> None: ...

    def get_expiry(self, key: str) -> float | None: ...

    def has(self, key: str) -> bool: ...

    def remove(self, key: str) -> None: ...

    def set_expiry(self, key: str, expires_at: float | None) -> None: ...
