from collections.abc import Callable
from typing import Protocol

from armaden.framework.types.result import Result


class CacheProtocol(Protocol):
    def add(self, key: str, value: object, ttl: int | None = None) -> Result[bool]: ...

    async def add_async(self, key: str, value: object, ttl: int | None = None) -> Result[bool]: ...

    def decrement(self, key: str, value: int = 1) -> Result[int]: ...

    async def decrement_async(self, key: str, value: int = 1) -> Result[int]: ...

    def forever(self, key: str, value: object) -> Result[bool]: ...

    async def forever_async(self, key: str, value: object) -> Result[bool]: ...

    def flush(self) -> Result[bool]: ...

    async def flush_async(self) -> Result[bool]: ...

    def forget(self, key: str) -> Result[bool]: ...

    async def forget_async(self, key: str) -> Result[bool]: ...

    def get(self, key: str, default: object = None) -> Result[object]: ...

    async def get_async(self, key: str, default: object = None) -> Result[object]: ...

    def get_default_cache_time(self) -> int: ...

    def get_prefix(self) -> str: ...

    def has(self, key: str) -> Result[bool]: ...

    async def has_async(self, key: str) -> Result[bool]: ...

    def increment(self, key: str, value: int = 1) -> Result[int]: ...

    async def increment_async(self, key: str, value: int = 1) -> Result[int]: ...

    def many(self, keys: list[str]) -> Result[dict[str, object]]: ...

    async def many_async(self, keys: list[str]) -> Result[dict[str, object]]: ...

    def missing(self, key: str) -> Result[bool]: ...

    async def missing_async(self, key: str) -> Result[bool]: ...

    def pull(self, key: str, default: object = None) -> Result[object]: ...

    async def pull_async(self, key: str, default: object = None) -> Result[object]: ...

    def put(self, key: str, value: object, ttl: int | None = None) -> Result[bool]: ...

    async def put_async(self, key: str, value: object, ttl: int | None = None) -> Result[bool]: ...

    def put_many(self, items: dict[str, object], ttl: int | None = None) -> Result[bool]: ...

    async def put_many_async(self, items: dict[str, object], ttl: int | None = None) -> Result[bool]: ...

    def remember(
        self,
        key: str,
        ttl: int,
        callback: Callable[[], object],
    ) -> Result[object]: ...

    async def remember_async(
        self,
        key: str,
        ttl: int,
        callback: Callable[[], object],
    ) -> Result[object]: ...

    def remember_forever(self, key: str, callback: Callable[[], object]) -> Result[object]: ...

    async def remember_forever_async(
        self,
        key: str,
        callback: Callable[[], object],
    ) -> Result[object]: ...

    def set_default_cache_time(self, seconds: int) -> None: ...

    def store(self, name: str | None = None) -> CacheProtocol: ...
