from __future__ import annotations

from typing import Protocol, override


class ContainerDunderProtocol(Protocol):
    def __contains__(self, key: object) -> bool: ...

    def __delitem__(self, key: object) -> None: ...

    def __getattr__(self, key: str) -> object: ...

    def __getitem__(self, key: object) -> object: ...

    @override
    def __setattr__(self, key: str, value: object) -> None: ...

    def __setitem__(self, key: object, value: object) -> None: ...
