from __future__ import annotations

import inspect
from collections.abc import Callable
from typing import Protocol

from armaden.framework.protocols.contextual_binding_builder_protocol import (
    ContextualBindingBuilderProtocol,
)


type Callback = Callable[..., object]
type Parameters = dict[object, object]


class ContainerMethodsProtocol(Protocol):
    def add_contextual_binding(
        self,
        concrete: object,
        abstract: object,
        implementation: object,
    ) -> None: ...

    def add_deferred_services(self, services: dict[object, type]) -> None: ...

    def after_resolving(
        self,
        abstract: object,
        callback: Callback | None = None,
    ) -> None: ...

    def after_resolving_attribute(self, attribute: object, callback: Callback) -> None: ...

    def alias(self, abstract: object, alias: object) -> None: ...

    def before_resolving(
        self,
        abstract: object,
        callback: Callback | None = None,
    ) -> None: ...

    def bind(
        self,
        abstract: object,
        concrete: object | None = None,
        shared: bool = False,
    ) -> None: ...

    def bind_based_on_closure_return_types(
        self,
        abstract: Callback,
        concrete: object | None = None,
        shared: bool = False,
    ) -> None: ...

    def bind_if(
        self,
        abstract: object,
        concrete: object | None = None,
        shared: bool = False,
    ) -> None: ...

    def bind_method(self, method: object, callback: Callback) -> None: ...

    def bound(self, abstract: object) -> bool: ...

    def build(self, concrete: object) -> object: ...

    def build_self_building_instance(self, concrete: type) -> object: ...

    def call(
        self,
        callback: object,
        parameters: Parameters | None = None,
        default_method: str | None = None,
    ) -> object: ...

    def call_method_binding(self, method: str, instance: object) -> object: ...

    def closure_return_types(self, closure: Callback) -> dict[str, type]: ...

    def current_environment_is(self, environments: object) -> bool: ...

    def currently_resolving(self) -> object | None: ...

    def discover_attribute_bindings(self, classes: list[type]) -> None: ...

    def drop_stale_instances(self, abstract: object) -> None: ...

    def extend(self, abstract: object, closure: Callback) -> None: ...

    def factory(self, abstract: object) -> Callback: ...

    def find_in_contextual_bindings(self, abstract: object) -> object | None: ...

    def fire_after_resolving_attribute_callbacks(
        self,
        attributes: list[object],
        obj: object,
    ) -> None: ...

    def fire_after_resolving_callbacks(self, abstract: object, obj: object) -> None: ...

    def fire_before_resolving_callbacks(
        self,
        abstract: object,
        parameters: Parameters | None = None,
    ) -> None: ...

    def fire_resolving_callbacks(self, abstract: object, obj: object) -> None: ...

    def flush(self) -> None: ...

    def forget_extenders(self, abstract: object) -> None: ...

    def forget_instance(self, abstract: object) -> None: ...

    def forget_instances(self) -> None: ...

    def forget_scoped_instances(self) -> None: ...

    def get(self, id: str) -> object: ...

    def get_alias(self, abstract: object) -> object: ...

    def get_bindings(self) -> dict[object, object]: ...

    def get_closure(self, abstract: object, concrete: object) -> Callback: ...

    def get_concrete(self, abstract: object) -> object: ...

    def get_concrete_binding_from_attributes(self, abstract: str) -> object: ...

    def get_contextual_concrete(self, abstract: object) -> object | None: ...

    def get_extenders(self, abstract: object) -> list[Callback]: ...

    def get_last_parameter_override(self) -> Parameters: ...

    def get_parameter_override(self, dependency: inspect.Parameter) -> object: ...

    def get_rebound_callbacks(self, abstract: object) -> list[Callback]: ...

    def has(self, id: str) -> bool: ...

    def has_method_binding(self, method: str) -> bool: ...

    def has_parameter_override(self, dependency: inspect.Parameter) -> bool: ...

    def instance(self, abstract: object, instance: object) -> object: ...

    def is_alias(self, name: object) -> bool: ...

    def is_buildable(self, concrete: object, abstract: object) -> bool: ...

    def is_shared(self, abstract: object) -> bool: ...

    def make(self, abstract: object, parameters: Parameters | None = None) -> object: ...

    def make_with(self, abstract: object, parameters: Parameters | None = None) -> object: ...

    def not_instantiable(self, concrete: object) -> None: ...

    def rebinding(self, abstract: object, callback: Callback) -> object | None: ...

    def rebound(self, abstract: object) -> None: ...

    def refresh(self, abstract: object, target: object, method: str) -> object | None: ...

    def remove_abstract_alias(self, searched: object) -> None: ...

    def resolve(
        self,
        abstract: object,
        parameters: Parameters | None = None,
        raise_events: bool = True,
    ) -> object: ...

    def resolve_builtin_default(self, parameter: inspect.Parameter) -> object: ...

    def resolve_class(self, parameter: inspect.Parameter) -> object: ...

    def resolve_dependencies(
        self,
        dependencies: list[inspect.Parameter],
    ) -> list[object]: ...

    def resolve_environment_using(self, callback: Callback | None) -> None: ...

    def resolve_from_attribute(
        self,
        attribute: object,
        dependency: inspect.Parameter | None = None,
    ) -> object: ...

    def resolve_primitive(self, parameter: inspect.Parameter) -> object: ...

    def resolve_variadic_class(self, parameter: inspect.Parameter) -> list[object]: ...

    def resolved(self, abstract: object) -> bool: ...

    def resolving(
        self,
        abstract: object,
        callback: Callback | None = None,
    ) -> None: ...

    def scoped(self, abstract: object, concrete: object | None = None) -> None: ...

    def scoped_if(self, abstract: object, concrete: object | None = None) -> None: ...

    def singleton(self, abstract: object, concrete: object | None = None) -> None: ...

    def singleton_if(self, abstract: object, concrete: object | None = None) -> None: ...

    def tag(self, abstracts: object, *tags: object) -> None: ...

    def tagged(self, tag: str) -> list[object]: ...

    def unresolvable_primitive(self, parameter: inspect.Parameter) -> None: ...

    def when(self, concrete: object) -> ContextualBindingBuilderProtocol: ...

    def when_has_attribute(self, attribute: str, handler: Callback) -> None: ...

    def wrap(self, callback: Callback, parameters: Parameters | None = None) -> Callback: ...
