from contextlib import AbstractContextManager
from typing import Protocol


class DatabaseSchemaBuilderProtocol(Protocol):
    def create(self, table: str) -> AbstractContextManager[object]: ...

    def drop(self, table: str) -> object: ...

    def drop_table_if_exists(self, table: str) -> object: ...

    def has_column(self, table: str, column: str) -> object: ...

    def has_table(self, table: str) -> object: ...

    def rename(self, from_table: str, to_table: str) -> object: ...

    def table(self, table: str) -> AbstractContextManager[object]: ...
