from typing import Protocol

from armaden.framework.types.result import Result


class FilesystemProtocol(Protocol):
    def copy(self, source: str, destination: str) -> Result[bool]: ...

    async def copy_async(self, source: str, destination: str) -> Result[bool]: ...

    def delete(self, path: str) -> Result[bool]: ...

    async def delete_async(self, path: str) -> Result[bool]: ...

    def delete_directory(self, path: str) -> Result[bool]: ...

    async def delete_directory_async(self, path: str) -> Result[bool]: ...

    def directories(self, directory: str | None = None) -> Result[list[str]]: ...

    async def directories_async(self, directory: str | None = None) -> Result[list[str]]: ...

    def driver(self) -> str: ...

    def exists(self, path: str) -> Result[bool]: ...

    async def exists_async(self, path: str) -> Result[bool]: ...

    def files(self, directory: str | None = None) -> Result[list[str]]: ...

    async def files_async(self, directory: str | None = None) -> Result[list[str]]: ...

    def get(self, path: str) -> Result[str | bytes]: ...

    async def get_async(self, path: str) -> Result[str | bytes]: ...

    def last_modified(self, path: str) -> Result[int]: ...

    async def last_modified_async(self, path: str) -> Result[int]: ...

    def make_directory(self, path: str) -> Result[bool]: ...

    async def make_directory_async(self, path: str) -> Result[bool]: ...

    def missing(self, path: str) -> Result[bool]: ...

    async def missing_async(self, path: str) -> Result[bool]: ...

    def move(self, source: str, destination: str) -> Result[bool]: ...

    async def move_async(self, source: str, destination: str) -> Result[bool]: ...

    def path(self, path: str) -> str: ...

    def put(self, path: str, contents: str | bytes) -> Result[bool]: ...

    async def put_async(self, path: str, contents: str | bytes) -> Result[bool]: ...

    def size(self, path: str) -> Result[int]: ...

    async def size_async(self, path: str) -> Result[int]: ...

    def temporary_url(self, path: str, expiration: int) -> str: ...

    def url(self, path: str) -> str: ...
