from collections.abc import Mapping
from datetime import datetime
from typing import Protocol


class FsspecFilesystemProtocol(Protocol):
    def cat(self, path: str) -> str | bytes: ...

    def copy(self, source: str, destination: str) -> None: ...

    def exists(self, path: str) -> bool: ...

    def info(self, path: str) -> Mapping[str, object]: ...

    def ls(self, path: str, detail: bool) -> list[Mapping[str, object]]: ...

    def modified(self, path: str) -> datetime: ...

    def mkdir(self, path: str, create_parents: bool) -> None: ...

    def move(self, source: str, destination: str) -> None: ...

    def pipe(self, path: str, data: bytes) -> None: ...

    def rm(self, path: str, recursive: bool = False) -> None: ...

    def size(self, path: str) -> int: ...

    def url(self, path: str, expires: int) -> str: ...