from __future__ import annotations

from collections.abc import Callable
from typing import Protocol


class HttpRequestProtocol(Protocol):
    async def body(self) -> bytes: ...

    def accepts(self, *content_types: str) -> bool: ...

    def accepts_html(self) -> bool: ...

    def accepts_json(self) -> bool: ...

    def all(self) -> dict[str, object]: ...

    def bearer_token(self) -> str | None: ...

    async def content(self) -> bytes: ...

    def except_(self, *keys: str) -> dict[str, object]: ...

    def expects_json(self) -> bool: ...

    def filled(self, key: str | list[str]) -> bool: ...

    def full_url(self) -> str: ...

    def full_url_is(self, *patterns: str) -> bool: ...

    def has(self, key: str | list[str]) -> bool: ...

    def has_file(self, key: str) -> bool: ...

    def has_header(self, key: str) -> bool: ...

    def has_session(self) -> bool: ...

    def header(self, key: str, default: object | None = None) -> str | None: ...

    def input(self, key: str | None = None, default: object | None = None) -> object: ...

    def file(self, key: str) -> object | None: ...

    def ip(self) -> str: ...

    def is_(self, pattern: str) -> bool: ...

    def is_authenticated(self) -> bool: ...

    def is_method(self, method: str) -> bool: ...

    def json(self, key: str | None = None, default: object | None = None) -> object: ...

    def missing(self, key: str | list[str]) -> bool: ...

    def method(self) -> str: ...

    def only(self, *keys: str) -> dict[str, object]: ...

    def path(self) -> str: ...

    def post(self, key: str | None = None, default: object | None = None) -> object: ...

    def query(self, key: str | None = None, default: object | None = None) -> object: ...

    def route_is(self, *names: str) -> bool: ...

    def session(self) -> object: ...

    def set_user(self, user: object) -> None: ...

    def user(self) -> object | None: ...

    def user_agent(self) -> str: ...

    def wants_json(self) -> bool: ...

    def when_filled(self, key: str, callback: Callable[..., object]) -> None: ...

    def when_has(self, key: str, callback: Callable[..., object]) -> None: ...

    def url(self) -> str: ...
