from enum import Enum
from pathlib import Path
from typing import Protocol, Self

from armaden.framework.protocols.task_protocol import TaskProtocol
from armaden.framework.types.process import ProcessStreamCallback


class ProcessBuilderProtocol[E: Enum, G](Protocol):
    def awaits(self, *references: str | type[object]) -> Self: ...

    def auto_restart(self) -> Self: ...

    def build(self) -> TaskProtocol[E]: ...

    def cwd(self, path: Path | str) -> Self: ...

    def depends_on(self, *references: str | type[object]) -> Self: ...

    def env(self, **values: str) -> Self: ...

    def long_running(self) -> Self: ...

    def on_stderr(self, callback: ProcessStreamCallback) -> Self: ...

    def on_stdout(self, callback: ProcessStreamCallback) -> Self: ...

    def submit(self) -> G: ...

    def timeout(self, seconds: float) -> Self: ...