from collections.abc import Awaitable
from typing import Protocol


class QueueJobProtocol(Protocol):
    def after(self) -> None: ...

    def before(self) -> None: ...

    def failed(self, exception: Exception) -> None: ...

    def handle(self) -> object | Awaitable[object]: ...
