from __future__ import annotations

from collections.abc import Sequence
from enum import Enum
from typing import Protocol, Self

from armaden.framework.types.schedule import (
    ScheduleCallback,
    ScheduleCondition,
    ScheduleHook,
)


class ScheduledEventProtocol[E: Enum, D, I](Protocol):
    @property
    def kind(self) -> E: ...

    def after(self, callback: ScheduleHook) -> Self: ...

    def append_output_to(self, path: str) -> Self: ...

    def at(self, time: str) -> Self: ...

    def before(self, callback: ScheduleHook) -> Self: ...

    def between(self, start: str, end: str) -> Self: ...

    def connection(self, name: str) -> Self: ...

    def cron(self, expression: str) -> Self: ...

    def daily(self) -> Self: ...

    def daily_at(self, time: str) -> Self: ...

    def days(self, values: Sequence[int]) -> Self: ...

    def definition(self) -> D: ...

    def description(self, value: str) -> Self: ...

    def environments(self, *values: str) -> Self: ...

    def even_in_maintenance_mode(self) -> Self: ...

    def every_fifteen_minutes(self) -> Self: ...

    def every_fifteen_seconds(self) -> Self: ...

    def every_five_minutes(self) -> Self: ...

    def every_five_seconds(self) -> Self: ...

    def every_four_hours(self, minute: int = 0) -> Self: ...

    def every_four_minutes(self) -> Self: ...

    def every_minute(self) -> Self: ...

    def every_odd_hour(self, minute: int = 0) -> Self: ...

    def every_second(self) -> Self: ...

    def every_seconds(self, value: int | float) -> Self: ...

    def every_six_hours(self, minute: int = 0) -> Self: ...

    def every_ten_minutes(self) -> Self: ...

    def every_ten_seconds(self) -> Self: ...

    def every_thirty_minutes(self) -> Self: ...

    def every_thirty_seconds(self) -> Self: ...

    def every_three_hours(self, minute: int = 0) -> Self: ...

    def every_three_minutes(self) -> Self: ...

    def every_three_seconds(self) -> Self: ...

    def every_two_hours(self, minute: int = 0) -> Self: ...

    def every_two_minutes(self) -> Self: ...

    def every_two_seconds(self) -> Self: ...

    def fridays(self) -> Self: ...

    def exclusive_worker(self) -> Self: ...

    def group(self, callback: ScheduleCallback) -> Self: ...

    def hourly(self) -> Self: ...

    def hourly_at(self, minute: int) -> Self: ...

    def last_day_of_month(self, time: str = '00:00') -> Self: ...

    def mondays(self) -> Self: ...

    def monthly(self) -> Self: ...

    def monthly_on(self, day: int, time: str = '00:00') -> Self: ...

    def name(self, value: str) -> Self: ...

    def on_connection(self, name: str) -> Self: ...

    def on_failure(self, callback: ScheduleHook) -> Self: ...

    def on_one_server(self) -> Self: ...

    def on_queue(self, name: str) -> Self: ...

    def on_success(self, callback: ScheduleHook) -> Self: ...

    def priority(self, value: int) -> Self: ...

    def quarterly(self) -> Self: ...

    def quarterly_on(self, day: int, time: str = '00:00') -> Self: ...

    def run_in_background(self) -> Self: ...

    def saturdays(self) -> Self: ...

    def send_output_to(self, path: str) -> Self: ...

    def skip(self, condition: ScheduleCondition) -> Self: ...

    def submit(self) -> I: ...

    def sundays(self) -> Self: ...

    def thursdays(self) -> Self: ...

    def tuesdays(self) -> Self: ...

    def timezone(self, value: str) -> Self: ...

    def twice_daily(self, first_hour: int, second_hour: int) -> Self: ...

    def twice_daily_at(
        self,
        first_hour: int,
        second_hour: int,
        minute: int = 0,
    ) -> Self: ...

    def unless_between(self, start: str, end: str) -> Self: ...

    def when(self, condition: ScheduleCondition) -> Self: ...

    def wednesdays(self) -> Self: ...

    def weekdays(self) -> Self: ...

    def weekends(self) -> Self: ...

    def weekly(self) -> Self: ...

    def weekly_on(self, day: int, time: str = '00:00') -> Self: ...

    def without_overlapping(self, minutes: int = 1440) -> Self: ...

    def yearly(self) -> Self: ...

    def yearly_on(self, month: int, day: int, time: str = '00:00') -> Self: ...
