from typing import Protocol


class SchedulerProtocol(Protocol):
    def get_jobs(self) -> list[object]: ...

    def remove_job(self, name: str) -> object: ...

    def shutdown(self, wait: bool = True) -> object: ...

    def start(self) -> object: ...
