from enum import Enum
from typing import Protocol, Self

from armaden.framework.protocols.task_protocol import TaskProtocol
from armaden.framework.types.task import TaskCallback, TaskStatusCallback


class TaskBuilderProtocol[E: Enum](Protocol):
    def build(self) -> TaskProtocol[E]: ...

    def description(self, value: str | None) -> Self: ...

    def exclusive_thread(self) -> Self: ...

    def name(self, value: str | None) -> Self: ...

    def on_initialize(self, callback: TaskCallback) -> Self: ...

    def on_run(self, callback: TaskCallback) -> Self: ...

    def on_shutdown(self, callback: TaskCallback) -> Self: ...

    def on_status(self, callback: TaskStatusCallback) -> Self: ...

    def shared_thread(self) -> Self: ...

    def with_auto_restart(self) -> Self: ...
