from enum import Enum
from typing import Protocol, Self

from armaden.framework.protocols.task_protocol import TaskProtocol
from armaden.framework.types.task import TaskCallback, TaskStatusCallback


class TaskBuilderProtocol[E: Enum](Protocol):
    def awaits(self, *references: str | type[object]) -> Self: ...

    def build(self) -> TaskProtocol[E]: ...

    def continue_on_failure(self) -> Self: ...

    def depends_on(self, *references: str | type[object]) -> Self: ...

    def description(self, value: str | None) -> Self: ...

    def exclusive_thread(self) -> Self: ...

    def long_running(self) -> Self: ...

    def name(self, value: str | None) -> Self: ...

    def on_initialize(self, callback: TaskCallback) -> Self: ...

    def on_run(self, callback: TaskCallback) -> Self: ...

    def on_shutdown(self, callback: TaskCallback) -> Self: ...

    def on_status(self, callback: TaskStatusCallback) -> Self: ...

    def priority(self, value: int) -> Self: ...

    def ready_timeout(self, seconds: float) -> Self: ...

    def restart(self, policy: str) -> Self: ...

    def retries(self, count: int, delay: float = 1.0, backoff: float = 2.0) -> Self: ...

    def shared_thread(self) -> Self: ...

    def timeout(self, seconds: float) -> Self: ...

    def with_auto_restart(self) -> Self: ...
