from armaden.framework.protocols.worker_protocol import WorkerProtocol
from typing import Protocol


class WorkerPoolProtocol[S: WorkerProtocol, E: WorkerProtocol](Protocol):
    async def acquire_exclusive(self, task_name: str) -> E: ...

    async def acquire_shared(self) -> S: ...

    async def release_exclusive(self, task_name: str) -> None: ...

    async def release_shared(self, worker: S) -> None: ...

    def shutdown(self) -> None: ...
