from typing import Dict, Protocol, Any, Self
from .supervisor import SupervisorInterface


class ApplicationInterface(Protocol):
    supervisor: SupervisorInterface

    def version(self) -> str: ...
    def environment(self, name: str, default: str | None = None) -> str | None: ...
    def config(self, key: str, default: Any | None = None) -> Any: ...

    def status(self) -> Dict[str, Any]: ...

    @classmethod
    def instance(cls) -> Self: ...
