import asyncio
from typing import Any, Protocol
from returns.result import Result
from .error import ErrorInterface
from .supervisor import SupervisorInterface


class KernelInterface(Protocol):
    def bootstrap(self) -> Result[None, ErrorInterface]: ...
    def handle(self, *args: Any, **kwargs: Any) -> Result[Any, ErrorInterface]: ...
    def terminate(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def application(self) -> 'CoreApplicationInterface': ...


class CoreApplicationInterface(Protocol):
    def register(self, provider: Any) -> Result[None, ErrorInterface]: ...
    def boot(self) -> Result[None, ErrorInterface]: ...
    def config(self, key: str, default: Any | None = None) -> Any: ...
    def version(self) -> str: ...
    def make(self, abstract: Any, parameters: Any | None = None) -> Any: ...
    @property
    def container(self) -> Any: ...
    @property
    def supervisor(self) -> SupervisorInterface: ...
    async def status(self) -> Result[Any, ErrorInterface]: ...
