from typing import Protocol


class DatagramTransportInterface(Protocol):
    async def connect_client(self, address: str, port: int) -> None: ...
    async def connect_server(self, address: str, port: int) -> None: ...
    async def close(self) -> None: ...
    async def send_data(self, data: bytes, *, address: tuple[str, int] | None = None) -> None: ...
