from typing import Protocol


class WrapperTransportInterface(Protocol):
    @property
    def address(self) -> str: ...

    @property
    def port(self) -> int: ...

    async def receive_datagram(self, data: bytes, address: str, port: int) -> None: ...
    async def handle_new_connection(self, address: str, port: int) -> None: ...
    async def handle_lost_connection(self, exception: Exception | None) -> None: ...
    async def handle_error(self, exception: Exception) -> None: ...
